
name: PHP Composer
on:
  push:
    branches: [ master ]

jobs: 
  run:
    name: Generate mo
    runs-on: ubuntu-latest
    steps: 
    - name: Generate mo
      run: for file in `find . -name "*.po"` ; do msgfmt -o ${file/.po/.mo} $file ; done

    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: ales-infotel
        author_email: alban.lesellier@infotel.com
        message: "Generate mo"
        add: "*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
